
class FlavourTextSeeds:
    def __init__(self):
        self.topics=[
            "LISTENING TO CHILDREN COUGHING",
            "JEWISH SHENANIGANS",
            "MONDAYS",
            "WHEN YOU SHAKE IT AND A LITTLE PEE FLIES OFF IN A RANDOM DIRECTION",
            "IMMIGRANTS",
            "BIG YET FLOPPY DICKS IN PORN",
            "CINEMA NOUVEAU",
            "BEING PART OF THE PROBLEM",
            "GUYS WHO CALL THEMSELVES FEMINIST",
            "SEEING THAT GUYS HEAD GET LITERALLY BLOWN OFF",
            "THAT JOKE ABOUT THE KID FALLING DOWN THE STAIRS",
            "CHILD SUPPORT EVEN THOUGH IT AINT HIS",
            "PEOPLE GOING INTO MUSIC STORES AND DROPTUNING ALL THE GUITARS",
            "THE FRENCH",
            "THE ENGLISH",
            "THE POWERS THAT BE",
            "SUPERHERO MOVIES WHERE THE GIRL HAS BETTER POWERS ARE LAME",
            "VAPING",
            "KETAMINE",
            "HEROIN",
            "SMALL HATCHBACKS WITH BIG ASS STEREO SYSTEMS IN THE BACK",
            "THE MEANINGLESS VOID THAT AWAITS US ALL",
            "WHERE THIS WAR IS GOING",
            "BEING BEATEN BY THEIR STEPDAD",
            "THINKING ABOUT JUMPING",
            "THE GUY NEXT TO YOU GIVING IT MORE THAN THREE SHAKES",
            "GIRLS WHO WEAR TOO MUCH MAKEUP",
            "THE FANCIER KIND YOU HAVE TO PAY MORE FOR",
            "HAVING WHITE GUILT AND LIKING IT",
            "BEING A LITTLE TIPSY AROUND GROPEY WRESTLERS",
            "CABLE TV",
            "THAT ONE PERSON AT PARTIES WHO ONLY TALKS ABOUT THEIR DIET",
            "WHEN YOUR PHONE AUTOCORRECTS TO EMBARRASSING WORDS",
            "SNEEZING WITHOUT A TISSUE NEARBY",
            "THE INEVITABLE CHAOS OF FAMILY REUNIONS FEATURING YOUR DRUNK STEPDAD",
            "THE NEVER-ENDING DEBATE OF TOILET PAPER ORIENTATION AND HOW IT AFFECTS YOUR SHITTING",
            "GETTING STUCK BEHIND SOMEONE WALKING SLOWLY",
            "THE IRONY OF PAYING FOR THERAPY TO TALK ABOUT MONEY PROBLEMS",
            "DEALING WITH TECHNOLOGY CUSTOMER SERVICE IN SOME FOREIGN COUNTRY",
            "TRYING TO END A PHONE CALL GRACEFULLY WITHOUT GIVING AWAY THAT YOU WERE BUSY JERKING OFF BEFORE ANSWERING",
            "WHEN YOUR FAVORITE TV SHOW GETS CANCELLED BECAUSE THE STAR GOT CANCELLED BY UNHINGED FEMINISTS",
            "THE DILEMMA OF CHOOSING A PROFILE PICTURE THAT HIDES YOUR BALD SPOT",
            "THE AGONY OF WAITING FOR A REPLY AFTER ASKING HER FOR NUDES",
            "THE QUIET JUDGMENT OF PUBLIC TRANSPORTATION WHEN YOU TAKE OUT YOUR PENIS",
            "THE PERPLEXITY OF ASSEMBLING FLAT PACK FURNITURE FOR THOSE WITH AMPUTATED HANDS",
            "THE CHAOS OF TRYING TO JUGGLE TOO MANY TASKS AT ONCE AND CHOOSING TO SMOKE WEED INSTEAD",
            "THE FRUSTRATION OF FINDING OUT YOUR FAVORITE RESTAURANT IS CLOSED DUE TO ONLY A MINOR RODENT INFESTATION",
            "THE TERROR OF REALIZING YOU FORGOT YOUR PSYCHO GIRLFRIEND'S BIRTHDAY",
            "THE STRESS OF TRYING TO MULTITASK WITHOUT SUCCESS THEN BLAMING IT ON A FAKE MENTAL DISORDER",
            "THE CHALLENGE OF WRITING AN EMAIL WITHOUT SOUNDING PASSIVE-AGGRESSIVE",
            "THE URGENCY OF FINDING A PUBLIC RESTROOM WHEN YOU'RE IN A HURRY, THEN SHITTING ON THE STREET INSTEAD",
            "THE AWKWARDNESS OF TRYING TO LEAVE A GROUP CONVERSATION WITHOUT GIVING AWAY YOUR ERECTION",
            "THE ANTICIPATION OF WAITING FOR THE RESULTS OF AN AIDS TEST",
            "THE EMBARRASSMENT OF REALIZING YOU'RE UNMUTED DURING A VIDEO CALL WHILE YOUR WIFE TELLS YOU SHE'S FILING FOR DIVORCE",
            "THE ANGST OF REALIZING YOU SENT A PICTURE OF YOUR ASSHOLE TO THE WRONG PERSON",
            "THE ART OF PICKING A LOCK WHEN YOU'RE LOCKED OUT AND DRUNK",
            "THE DARK ALLURE OF SECRET UNDERGROUND CLUBS",
            "THE UNDERWORLD OF ILLEGAL STREET RACING",
            "THE SHADOWY WORLD OF BLACK MARKET TRANSACTIONS",
            "THE INTENSITY OF A HIGH-STAKES POKER GAME WHILE A HOOKER CLUMSILY TRIES TO GRIND HER ASS IN YOUR FACE",
            "THE DANGEROUS ATTRACTION OF FORBIDDEN ROMANCES",
            "THE SEEDY BACKROOM DEALS OF CORRUPT POLITICIANS",
            "THE GRITTY REALITY OF UNDERCOVER INVESTIGATIONS",
            "THE TANGLED WEB OF ORGANIZED CRIME SYNDICATES",
            "THE SECRET LIVES OF HIGH-END CALL-GIRLS",
            "THE GRIM REALITY OF ADDICTION AND REHAB",
            "THE EROTIC MYSTIQUE OF EXCLUSIVE INVITATION-ONLY PARTIES",
            "THE HARSH REALITY OF LIFE ON THE STREETS",
            "THE CUTTHROAT WORLD OF ILLEGAL DRUG TRAFFICKING",
            "THE HIDDEN DEPTHS OF THE DARK WEB",
            "THE RAW INTENSITY OF UNDERGROUND FIGHT CLUBS",
            "THE FORBIDDEN TEMPTATION OF ADULTERATED PLEASURES",
            "THE UNDERBELLY OF CITY NIGHTLIFE AND DEBAUCHERY",
            "THE DARK SECRETS BEHIND CLOSED DOORS IN SUBURBIA",
            "THE SINISTER SIDE OF BIG CITY CORPORATE POWER",
            "THE UNEXPECTED CONSEQUENCES OF DARING HEISTS",
            "THE UNDERWORLD OF HIGH-STAKES GAMBLING",
            "THE SHADY DEALINGS OF SMUGGLERS AND CONTRABAND",
            "THE SEEDY REALITY OF ILLEGAL GAMBLING DENS",
            "THE MORAL AMBIGUITY OF UNDERCOVER COPS",
            "THE TWISTED WORLD OF DOMESTIC SUSPICIONS AND BETRAYALS",
            "THE GRIM OUTLOOK OF LOVE IN THE TIME OF CONFLICT",
            "THE TANGLED WEBS SPUN BY SEXUAL PREDATORS",
            "THE HIDDEN ADDICTIONS BEHIND CLOSED DOORS",
            "THE STRANGE WORLD OF COLLECTING HUMAN HAIR",
            "THE ODD PRACTICE OF TAXIDERMY ON PET FISH AND HOW IT AFFECTS YOUR RELATIONSHIP WITH YOUR KIDS",
            "THE EERIE PRACTICE OF KEEPING TAXIDERMIED PETS",
            "WOMEN WHO LEAVE HAIR EVERYWHERE BUT THE DRAIN",
            "NOT KNOWING WHAT SHE WANTS TO EAT BUT SHOOTING DOWN EVERY SUGGESTION",
            "WOMEN TAKING HOURS TO GET READY",
            "WOMEN SAYING 'NOTHING'S WRONG' WHEN SOMETHING IS CLEARLY WRONG",
            "WOMEN NEVER BEING ABLE TO FIND ANYTHING IN HER PURSE",
            "WOMEN BUYING TOO MANY SHOES AND NEVER WEARING HALF OF THEM",
            "WOMEN NEVER FINISHING A SINGLE THOUGHT",
            "WOMEN NEVER BEING READY WHEN IT'S TIME TO LEAVE",
            "WOMEN NEEDING TO TALK ABOUT EVERYTHING",
            "PISSING OFF YOUR WIFE BY LEAVING EMPTY CARTONS IN THE FRIDGE",
            "WHEN YOUR SECRET LOVER LEAVES HAIR TIES ALL OVER THE PLACE AND YOUR WIFE FINDS ONE",
            "WOMEN BRINGING UP OLD ARGUMENTS IN NEW DISCUSSIONS AND THEN BLAMING IT ON SEXISM",
            "YOUR WIFE YELLING AT YOU FOR NEVER CLOSING CABINET DOORS",
            "OCCASIONALLY THINKING YOU CAN READ HER MIND WHEN ALL YOU CAN THINK ABOUT IS BANGING HER",
            "WITHOLDING SEX FOR FORGETTING HER BIRTHDAY",
            "GETTING STUCK BEHIND A FLOCK OF FAT SLOW-WALKING TOURISTS IN A BUSY CITY",
            "REALIZING YOU'VE BEEN REPLYING TO A SPAM EMAIL THINKING IT WAS LEGIT AND YOU'RE NOW BROKE",
            "TRYING TO OPEN A DOOR BY PUSHING WHEN IT CLEARLY SAYS 'PULL' AND HAVING A FAT KID LAUGH AT YOU AS A RESULT",
            "GETTING INTERRUPTED MID-STORY AND FORGETTING WHERE YOU LEFT OFF BECAUSE YOU'RE A POTHEAD",
            "DROPPING YOUR FORK WHILE TRYING TO EAT SPAGHETTI, AND WHEN YOU BEND TO PICK IT UP, YOU ACCIDENTLY GET A GLIMPSE OF YOUR DATE'S PUSSY",
            "GETTING INTO THE WRONG CAR IN A PARKING LOT AND ONLY REALIZING IT WHEN THE OWNER RETURNS AND THREATENS TO SHOOT YOU",
            "ACCIDENTALLY SWIPING LEFT ON SOMEONE YOU ACTUALLY LIKED ON A DATING APP",
            "REALIZING THE TIP OF YOUR FORESKIN HAS BEEN POKING OUT OF YOUR OPEN FLY ALL DAY",
            "GETTING LOCKED OUT OF YOUR OWN HOUSE BY YOUR WIFE BECAUSE YOU CAN'T STOP DAYDRINKING",
            "TRYING TO HOLD A SNEEZE IN DURING A QUIET MOVIE AND IT COMES OUT LIKE A BELLOW AND YOU PISS YOURSELF",
            "REALIZING YOU'VE BEEN WEARING A WATCH MADE FOR WOMEN",
            "CONVINCING YOURSELF THAT YOU'RE THE MAIN CHARACTER IN A REALITY TV SHOW AND EVERYONE ELSE IS AN IDIOT",
            "TRYING TO SNEAK INTO A ZOO AT NIGHT TO PRETEND YOU'RE NOAH ON THE ARK",
            "MAKING TERRIBLE MAJOR LIFE DECISIONS BASED ON THE WISDOM OF YOUR MAGIC 8-BALL",
            "GETTING FRAMED FOR DOMESTIC TERRORISM",
            "CONDUCTING A SOCIAL EXPERIMENT TO SEE IF WOMEN LIKE YOU MORE IF YOU TRAUMA DUMP",
            "THE PARADOX OF DECAF COFFEE AND HOW IT PROMOTES EXTREMISM",
            "WHEN YOU CAN'T REMEMBER IF YOU TURNED OFF THE STOVE AND YOUR WIFE DIES IN A HOUSEFIRE",
            "THE DILEMMA OF CHOOSING BETWEEN TWO EQUALLY UNAPPEALING FLAVORS OF ICE CREAM",
            "THE AWKWARDNESS OF BEING THE ONLY ONE WHO DIDN'T GET THE JOKE AND THEN LATER REALIZING THEY WERE LAUGHING AT YOU",
            "WHEN YOU GET INTERRUPTED RIGHT WHEN YOU'RE ABOUT TO SAY SOMETHING IMPORTANT",
            "THE STRUGGLE OF UNZIPPING YOUR PANTS AND GETTING YOUR FORESKIN STUCK IN THE ZIPPER",
            "WHEN YOU HOLD THE DOOR FOR SOMEONE AND THEY DON'T SAY THANK YOU SO YOU CALL THEM A SLUR",
            "THE FRUSTRATION OF FORGETTING TO PUT ON DEODORANT AND REALIZING MID-DAY",
            "THE PECULIARITY OF DAYDREAMING ABOUT YOUR CUTE COLLEAGUE'S PANTIES",
            "THE DISCOMFORT OF HAVING TO MAKE SMALL TALK WITH A STRANGER IN THE ELEVATOR WHO'S CLEARLY ON HIS WAY TO KILL HIS WIFE'S LOVER",
            "THE NOSTALGIA OF FINDING AN OLD TOY YOU USED TO LOVE AS A CHILD EVEN THOUGH YOUR STEPDAD BEAT YOU BECAUSE HE THOUGHT IT WOULD MAKE YOU GAY",
            "THE ANNOYANCE OF HAVING TO REPEAT YOURSELF MULTIPLE TIMES BECAUSE YOU'RE WAY TOO HIGH",
            "WHEN YOU CAN'T REMEMBER IF YOU SHAMPOOED YOUR HAIR OR NOT, FORGETTING THAT YOU DIDN'T EVEN WASH YOUR ASS",
            "WHEN YOU GO TO TAKE A SIP OF YOUR DRINK AND REALIZE IT'S SPIKED, BUT DRINK IT ANYWAY BECAUSE YOU CAN'T AFFORD ANOTHER",
            "THE DISAPPOINTMENT OF LOOKING FORWARD TO LEFTOVERS AND FINDING OUT YOUR FAT SISTER ATE THEM",
            "WHEN YOU CAN'T STOP THINKING ABOUT SOMETHING EMBARRASSING YOU DID YEARS AGO THAT GOT YOU ON A NO-FLY LIST",
            "THE RELIEF OF FINDING OUT YOU MISSED A TEST AND IT GOT POSTPONED, BUT IT WAS AN AIDS TEST",
            "THE DISAPPOINTMENT OF OPENING THE FRIDGE AND FINDING NOTHING TO EAT BECAUSE YOU SPENT ALL YOUR MONEY ON INSTANT LOTTO",
            "THE ANXIETY OF SENDING YOUR MOTHER-IN-LAW A TEXT AND THEN SEEING THE '...' FOR A LONG TIME",
            "THE RELIEF OF FINDING OUT THE SPIDER YOU SAW WAS ACTUALLY A FLECK OF SHIT",
            "THE ANNOYANCE OF GETTING STUCK BEHIND A SLOW DRIVER IN THE FAST LANE",
            "THE RELIEF OF FINALLY FINDING YOUR LOST CAT AND LATER REALIZING IT'S ACTUALLY A DIFFERENT CAT",
            "THE DISAPPOINTMENT OF REALIZING YOU'RE OUT OF TOILET PAPER MID-USE AND HAVE TO RESORT TO WIPING WITH YOUR WIFE'S EXPENSIVE TOWEL",
            "WHEN YOU THINK IT'S A HOLIDAY BUT IT'S ACTUALLY NOT AND YOU HAVE TO GO TO WORK",
            "WHEN YOU CAN'T REMEMBER IF YOU LOCKED YOUR CAR AND THEN RETURNING TO FIND IT STOLEN",
            "THE ANNOYANCE OF GETTING A HAIRCUT AND THEN REALIZING YOU HATE IT MAKES YOU LOOK LIKE A TOOL",
            "THE AWKWARDNESS OF MAKING EYE CONTACT WITH SOMEONE WHILE EATING A BANANA",
            "THE FRUSTRATION OF TRYING TO TAKE A NAP AND BEING UNABLE TO FALL ASLEEP BECAUSE YOUR NEIGHBOUR WON'T BEAT HIS WIFE QUIETLY",
            "TRYING TO COME UP WITH AN EXCUSE WHEN YOU TELL THE STRIPPER WHY YOU CAN'T TIP HER",
            "THE ANNOYANCE OF GETTING STUCK BEHIND A SLOW DRIVER IN THE FAST LANE",
            "BEING HARASSED BY A JAPANESE NOVELTY VENDING MACHINE AND NOBODY ELSE BELIEVING YOU",
            "AN ELABORATE LIE YOU TOLD YOUR BOSS TO GET OFF WORK SPIRALLING OUT OF CONTROL AND TAKING UP MOST OF YOUR TIME"
        ]
        self.topicDict={}
        self.compactPersDict={}
        self.compactPers3rdDict={}
        
        self.languages=[
            "Afrikaans",
            "English"
            '''
            ,
            "French"
            '''
        ]
        
        self.personalitySeeds=[
            "a real jerk sometimes.",
            "a little unhinged, -and frankly- not all there.",
            "borderline mentally impaired.",
            "friendly enough, except when he's sober.",
            "amiable and easy to get along with.",
            "autistic.",
            "an avid birdwatcher.",
            "a man of many fetishes.",
            "interested in cryptocurrency and won't shut up about it.",
            "wanted for homicide in most countries except this one.",
            "a cool guy with a cool outlook on life.",
            "a bitter old bastard.",
            "chill and friendly.",
            "in debt to a bunch of really bad people.",
            "unlikely to survive more than a few days.",
            "high on life.",
            "not worth a bodybag.",
            "a male feminist and lets people know it.",
            "a total manchild.",
            "not capable of sustaining meaningful relationship, and often has serious moodswings.",
            "an unmedicated mess, with few redeeming qualities.",
            "willing to betray friends in the pursuit of his own goals.",
            "incapable of getting and holding a strong erection.",
            "a serious misogynist.",
            "a man that hates women because he watches way too much Alpha Male content online.",
            "bad with handling money",
            "a cruel man that enjoys the suffering of others.",
            "someone who has absolutely no redeeming qualitites.",
            "someone who smokes marijuana all day every day, and his intellect suffers as a result. Most days he can barely remember his own name.",
            "someone who steals a lot, as he has no respect for other peoples' possessions.",
            "a died-in-the-wool incel that despises women because of his lack of redeeming qualities.",
            "a man that has no direction in life.",
            "a thief and a liar.",
            "kinda boring.",
            "a good man.",
            "wanted for numerous sex-crimes.",
            "obsessed with Anime.",
            "someone suffering from crippling insecurity.",
            "some who takes what he has for granted.",
            "not to be trusted around children.",
            "kinda creepy and avoided by most.",
            "a burden on the economy due to his gambling debt",
            "obsessed with tracking his girlfriend's menstrual cycle.",
            "someone who gets all his information from social media and doesn't understand that he's only consuming outlier content.",
            "someone who doesn't bring anything to the table in terms of dating.",
            "emaculated by the fact that his girlfriend makes more money than him.",
            "angered by even the smallest of things.",
            "uncomminicative and gives terse replies.",
            "believes God is out to get him.",
            "someone who doesn't like to share.",
            "someone with a very, VERY low IQ.",
            "beats his wife and ejoys it.",
            "addicted to online shopping.",
            "always wondering if his girlfriend is cheating on him.",
            "always broke and trying to borrow money from his friends.",
            "an asshole because he fakes having cancer to get attention.",
            "a sleezeball and a scammer.",
            "infested with STI's and likes to brag about it.",
            "a chronic whoremongerer, always cheating on his loyal spouse.",
            "unreliable when it comes to parenting.",
            "a man without any kind of moral compass.",
            "unable to hold a job for very long, and is already looking for a way off the front.",
            "terrible in every conceivable way.",
            "plagued by his antisocial personality disorder and struggles to make friends.",
            "someone with undiagnosed schizophrenia.",
            "a real asshole.",
            "unapologetically racist, and makes others feel uncomfortable through this.",
            "proudly racist and doesn't see a problem with that.",
            "an Afrikaner with problematic nostalgia for the 'old days'",
            "a wheeler-dealer without no aptitude for wheeling or dealing.",
            "sick of the apparent futility of it all.",
            "about to crack and on the verge of going on a killing spree.",
            "secretly a spy for the enemy.",
            "crude, unhinged, and prone to saying inappropriate things.",
            "riddled with lifestyle diseases.",
            "a man who really enjoys war and wants to kill as many people as possible.",
            "only here to shoot people, be they civilian, friendly, or enemy.",
            "an uncultered slob who gets all his information from television.",
            "someone who tries to steer every conversation to how much he loves his wife.",
            "a man with an unhealthy obsession with the bowel movements of others.",
            "always on the verge of breaking up with his girlfriend.",
            "suspected of killing his mother, and neither confirms nor denies it.",
            "an aspiring rapper with absolutely zero skill.",
            "a loser who misses his piano because its the only real friend he ever had.",
            "a chronic bedwetter.",
            "one of those guys that maintains weed is not addictive even though he can't go a single day without smoking.",
            "a deadbeat who mooches off his girlfriend's hard-earned money.",
            "an escaped convict on the run from the law.",
            "a strong homophobe clearly compensating for his inability to accept the fact that he himself is gay."
            "a guy who says he does heroin as a 'joke' but is clearly an addicted wreck.",
            "a nepo-baby who is upset his dad couldn't get him off the front.",
            "a trust-fund baby who spent all his money on hookers and blow.",
            "unable to properly keep his rifle in working order.",
            "sick and tired of being sick and tired.",
            "someone who doesn't quite grasp that his 12-Step program means he can't use drugs anymore.",
            "a simpleton, a creep, and a real dumbass.",
            "thinks he knows something about everything but knows nothing about anything."
        ]

        self.personalitySeedsCompact=[
            "a real jerk sometimes.",
            "a little unhinged, -and frankly- not all there.",
            "borderline mentally impaired.",
            "friendly enough, except when you're sober.",
            "amiable and easy to get along with.",
            "autistic.",
            "an alcoholic.",
            "a Satanist for social media purposes.",
            "quite the Romeo.",
            "bitter because your brother is more successful than you.",
            "an avid birdwatcher.",
            "a man of many fetishes.",
            "interested in cryptocurrency and won't shut up about it.",
            "wanted for homicide in most countries except this one.",
            "clumsily trying to hide the fact that you are a reincarnation of Hitler.",
            "a cool guy with a cool outlook on life.",
            "a bitter old bastard.",
            "chill and friendly.",
            "in debt to a bunch of really bad people.",
            "unlikely to survive more than a few days.",
            "high on life.",
            "not worth a bodybag.",
            "someone who is into birdwatching for strange sexual reasons.",
            "a male feminist and lets people know it.",
            "a total manchild.",
            "not capable of sustaining meaningful relationship, and often has serious moodswings.",
            "an unmedicated mess, with few redeeming qualities.",
            "willing to betray friends in the pursuit of your own goals.",
            "incapable of getting and holding a strong erection.",
            "a serious misogynist.",
            "a man that hates women because you watch way too much Alpha Male content online.",
            "bad with handling money",
            "a cruel man who enjoys the suffering of others.",
            "someone who has absolutely no redeeming qualitites.",
            "someone who smokes marijuana all day every day, and your intellect suffers as a result. Most days you can barely remember your own name.",
            "someone who steals a lot, as has no respect for other peoples' possessions.",
            "a died-in-the-wool incel that despises women because of your lack of redeeming qualities.",
            "a man that has no direction in life.",
            "always looking to start a fight.",
            "hot tempered and a real loose cannon.",
            "impotent, nasty, and not worth a damn to anyone.",
            "kinda creepy and say inappropriate things in every conversation.",
            "not allowed to be near children.",
            "someone who'd love to have kids one day but displays all the characteristics of someone who'd get his children killed through negligence.",
            "a thief and a liar.",
            "kinda boring.",
            "someone with a severe stutter.",
            "thinks everyone besides you is a robot.",
            "someone who never finishes a thought.",
            "a good man.",
            "wanted for numerous sex-crimes.",
            "someone who can't stop bragging about how many DUI's he has.",
            "obsessed with Anime.",
            "someone suffering from crippling insecurity.",
            "someone who takes what you have for granted.",
            "not to be trusted around children.",
            "kinda creepy and avoided by most.",
            "a burden on the economy due to your gambling debt.",
            "obsessed with tracking your girlfriend's menstrual cycle.",
            "someone who gets all your information from social media and doesn't understand that you're only consuming outlier content.",
            "someone who doesn't bring anything to the table in terms of dating.",
            "emaculated by the fact that your girlfriend makes more money than you.",
            "angered by even the smallest of things.",
            "uncomminicative and gives terse replies.",
            "obsessed with 'I hate my wife' boomer jokes.",
            "someone who believes God is out to get you.",
            "someone who doesn't like to share.",
            "someone with a very, VERY low IQ.",
            "someone who beats his wife and ejoys it.",
            "addicted to online shopping.",
            "always wondering if your girlfriend is cheating on you.",
            "always broke and trying to borrow money from your friends.",
            "an asshole because you fake having cancer to get attention.",
            "a sleezeball and a scammer.",
            "infested with STI's and like to brag about it.",
            "a chronic whoremongerer, always cheating on your loyal spouse.",
            "unreliable when it comes to parenting.",
            "a man without any kind of moral compass.",
            "unable to hold a job for very long, and is already looking for a way off the front.",
            "terrible in every conceivable way.",
            "plagued by your antisocial personality disorder and struggles to make friends.",
            "someone with undiagnosed schizophrenia.",
            "a real asshole.",
            "unapologetically racist, and makes others feel uncomfortable through this.",
            "proudly racist and doesn't see a problem with that.",
            "an Afrikaner with problematic nostalgia for the 'old days'",
            "a wheeler-dealer without no aptitude for wheeling or dealing.",
            "sick of the apparent futility of it all.",
            "about to crack and on the verge of going on a killing spree.",
            "secretly a spy for the enemy.",
            "crude, unhinged, and prone to saying inappropriate things.",
            "riddled with lifestyle diseases.",
            "a man who really enjoys war and wants to kill as many people as possible.",
            "only here to shoot people, be they civilian, friendly, or enemy.",
            "an uncultered slob who gets all his information from television.",
            "someone who tries to steer every conversation to how much you love your wife.",
            "a man with an unhealthy obsession with the bowel movements of others.",
            "always on the verge of breaking up with your girlfriend.",
            "suspected of killing your mother, and neither confirms nor denies it.",
            "an aspiring rapper with absolutely zero skill.",
            "a loser who misses your piano because its the only real friend you ever had.",
            "a chronic bedwetter.",
            "one of those guys that maintains weed is not addictive even though you can't go a single day without smoking.",
            "a deadbeat who mooches off your girlfriend's hard-earned money.",
            "an escaped convict on the run from the law.",
            "a strong homophobe clearly compensating for your inability to accept the fact that you yourself are gay."
            "a guy who says you does heroin as a 'joke' but is clearly an addicted wreck.",
            "a nepo-baby who is upset your dad couldn't get you off the front.",
            "a trust-fund baby who spent all your money on hookers and blow.",
            "unable to properly keep your rifle in working order.",
            "sick and tired of being sick and tired.",
            "someone who doesn't quite grasp that your 12-Step program means you can't use drugs anymore.",
            "a simpleton, a creep, and a real dumbass.",
            "thinks you know something about everything but knows nothing about anything.",
            "infested with strange diseases from Africa and thinks it's cool.",
            "not entirely sure which side you're fighting for in this war.",
            "someone who's desperatedly trying to hide the fact that he can't read.",
            "unable to remember his girlfriend's birthday.",
            "an aspiring serial killer that can't stomach murder.",
            "bitter, a failure, and unable to impress women. You blame it all on socialism and gays.",
            "someone who suspects they're accidently fighting on the wrong side but is too agreeable to mention it.",
            "a crypto trader that really doesn't understand crypto."
        ]

        self.personalitySeedsCompact3rdPerson=[
            "a real jerk sometimes.",
            "a little unhinged, -and frankly- not all there.",
            "borderline mentally impaired.",
            "friendly enough, except when they're sober.",
            "amiable and easy to get along with.",
            "autistic.",
            "an alcoholic.",
            "a Satanist for social media purposes.",
            "quite the Romeo.",
            "bitter because his younger brother is more successful than him.",
            "an avid birdwatcher that hates birds.",
            "a man of many fetishes.",
            "interested in cryptocurrency and won't shut up about it.",
            "wanted for homicide in most countries except this one.",
            "clumsily trying to hide the fact that they are a reincarnation of Hitler.",
            "a cool guy with a cool outlook on life.",
            "a bitter old bastard.",
            "chill and friendly.",
            "in debt to a bunch of really bad people.",
            "unlikely to survive more than a few days.",
            "high on life.",
            "not worth a bodybag.",
            "someone who is into birdwatching for strange sexual reasons.",
            "a male feminist and lets people know it.",
            "a total manchild.",
            "not capable of sustaining meaningful relationship, and often has serious moodswings.",
            "an unmedicated mess, with few redeeming qualities.",
            "willing to betray friends in the pursuit of his own goals.",
            "incapable of getting and holding a strong erection.",
            "a serious misogynist.",
            "a man that hates women because he watches way too much Alpha Male content online.",
            "bad with handling money",
            "a cruel man who enjoys the suffering of others.",
            "someone who has absolutely no redeeming qualitites.",
            "someone who smokes marijuana all day every day, and his intellect suffers as a result. Most days you can barely remember your own name.",
            "steals a lot, as has no respect for other peoples' possessions.",
            "a died-in-the-wool incel that despises women because of his lack of redeeming qualities.",
            "a man that has no direction in life.",
            "always looking to start a fight.",
            "hot tempered and a real loose cannon.",
            "impotent, nasty, and not worth a damn to anyone.",
            "kinda creepy and says inappropriate things in every conversation.",
            "not allowed to be near children.",
            "someone who'd love to have kids one day but displays all the characteristics of someone who'd get his children killed through negligence.",
            "a thief and a liar.",
            "kinda boring.",
            "someone with a severe stutter.",
            "thinks everyone besides them is a robot.",
            "someone who never finishes a thought.",
            "a good man.",
            "wanted for numerous sex-crimes.",
            "someone who can't stop bragging about how many DUI's he has.",
            "obsessed with Anime.",
            "someone suffering from crippling insecurity.",
            "someone who takes what he has for granted.",
            "not to be trusted around children.",
            "kinda creepy and avoided by most.",
            "a burden on the economy due to their gambling debt.",
            "obsessed with tracking his girlfriend's menstrual cycle.",
            "someone who gets all his information from social media and doesn't understand that they're only consuming outlier content.",
            "someone who doesn't bring anything to the table in terms of dating.",
            "emaculated by the fact that their girlfriend makes more money than him.",
            "angered by even the smallest of things.",
            "uncomminicative and gives terse replies.",
            "obsessed with 'I hate my wife' boomer jokes.",
            "someone who believes God is out to get him.",
            "someone who doesn't like to share.",
            "someone with a very, VERY low IQ.",
            "someone who beats his wife and ejoys it.",
            "addicted to online shopping.",
            "always wondering if his girlfriend is cheating on him.",
            "always broke and trying to borrow money from his friends.",
            "an asshole because he fakes having cancer to get attention.",
            "a sleezeball and a scammer.",
            "infested with STI's and likes to brag about it.",
            "a chronic whoremongerer, always cheating on his loyal spouse.",
            "unreliable when it comes to parenting.",
            "a man without any kind of moral compass.",
            "unable to hold a job for very long, and is already looking for a way off the front.",
            "terrible in every conceivable way.",
            "plagued by his antisocial personality disorder and struggles to make friends.",
            "someone with undiagnosed schizophrenia.",
            "a real asshole.",
            "unapologetically racist, and makes others feel uncomfortable through this.",
            "proudly racist and doesn't see a problem with that.",
            "an Afrikaner with problematic nostalgia for the 'old days'",
            "a wheeler-dealer without no aptitude for wheeling or dealing.",
            "sick of the apparent futility of it all.",
            "about to crack and on the verge of going on a killing spree.",
            "secretly a spy for the enemy.",
            "crude, unhinged, and prone to saying inappropriate things.",
            "riddled with lifestyle diseases.",
            "a man who really enjoys war and wants to kill as many people as possible.",
            "only here to shoot people, be they civilian, friendly, or enemy.",
            "an uncultered slob who gets all his information from television.",
            "someone who tries to steer every conversation to how much he loves his wife.",
            "a man with an unhealthy obsession with the bowel movements of others.",
            "always on the verge of breaking up with his girlfriend.",
            "suspected of killing his mother, and neither confirms nor denies it.",
            "an aspiring rapper with absolutely zero skill.",
            "a loser who misses his piano because its the only real friend he ever had.",
            "a chronic bedwetter.",
            "one of those guys that maintains weed is not addictive even though he can't go a single day without smoking.",
            "a deadbeat who mooches off his girlfriend's hard-earned money.",
            "an escaped convict on the run from the law.",
            "a strong homophobe clearly compensating for his inability to accept the fact that he himself is gay."
            "a guy who says he does heroin as a 'joke' but is clearly an addicted wreck.",
            "a nepo-baby who is upset his dad couldn't get you off the front.",
            "a trust-fund baby who spent all his money on hookers and blow.",
            "unable to properly keep his rifle in working order.",
            "sick and tired of being sick and tired.",
            "someone who doesn't quite grasp that your 12-Step program means he can't use drugs anymore.",
            "a simpleton, a creep, and a real dumbass.",
            "thinks he knows something about everything but knows nothing about anything.",
            "infested with strange diseases from Africa and thinks it's cool.",
            "not entirely sure which side he's fighting for in this war.",
            "someone who's desperatedly trying to hide the fact that he can't read.",
            "unable to remember his girlfriend's birthday.",
            "an aspiring serial killer that can't stomach murder.",
            "bitter, a failure, and unable to impress women. He blames it all on socialism and gays.",
            "someone who suspects they're accidently fighting on the wrong side but is too agreeable to mention it.",
            "a crypto trader that really doesn't understand crypto."
        ]
                                
        self.authorSeeds=[
            "Stephen King",
            "Chuck Palahniuk",
            "Ian McEwan",
            "Aleister Crowley",
            "Cormac McCarthy",
            "Vladimir Nabokov"
        ]
    
    
    def toDictTopics(self):
        cntr=0
        for x in self.topics:
            self.topicDict[cntr]=x
            cntr+=1
        return self.topicDict    
    def toDictPersonalitySeedsCompact(self):
        cntr=0
        for x in self.personalitySeedsCompact:
            self.compactPersDict[cntr]=x
            cntr+=1
        return self.compactPersDict    
    def toDictpersonalitySeedsCompact3rdPerson(self):
        cntr=0
        for x in self.personalitySeedsCompact3rdPerson:
            self.compactPers3rdDict[cntr]=x
            cntr+=1
        return self.compactPers3rdDict